<a href="https://colab.research.google.com/github/ivan74rus/DS/blob/main/%D0%9B%D0%B8%D0%BD%D0%90%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B0_%D0%BA%D0%BE%D0%B4_%D0%BF%D0%B5%D1%80%D1%81%D0%BE%D0%BD_%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

In [1]:
#подключить гугл диск
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# импорты
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [3]:
# константы
LOCAL_DATA_PATH = '/content/drive/MyDrive/DS/' 
DATA_FILE = 'insurance.csv'

## Загрузка данных

In [4]:
df = pd.read_csv(f'{LOCAL_DATA_PATH}/{DATA_FILE}')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


In [5]:
df.head(5)

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0

In [6]:
df['Страховые выплаты'].unique()

array([0, 1, 2, 3, 5, 4])

## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Ответ:** Качество линейной регрессии не дошло ухудшиться.

**Обоснование:**      
Имеем  $X_1 = X * P$, где P квадратная обратимая матрица для кодировки данных.    

Нужно доказать:      
$X_1w_1 = Xw$.               
$XPw_1 = Xw$                        
$w_1 = P^{-1}w $                    
$w_1 =P^{-1} * (X^T X)^{-1} X^T y $  , это исходная формула 

Доказательство.
 
$w_1 = ((X_1)^T X_1)^{-1} (X_1)^T y$ , ставим $X_1 = XP$     
$w_1 = ((XP)^T (XP))^{-1} (XP)^T y$  ,   применяем $(AB)^T = B^T A^T$       
$w_1 = (P^TX^TXP)^{-1}  P^TX^T y$   , выделим  $X^TX$ как отдельную  
$w_1 = (P^T(X^TX)P)^{-1}  P^TX^T y$ , используем  $(ABC)^{-1} = (C)^{-1} (AB)^{-1}$ для выноса $P$   
$w_1 = P^{-1}(P^T(X^TX))^{-1}  P^TX^T y$, используем  $(AB)^{-1} = B^{-1} A^{-1}$ для выноса $P^T$     
$w_1 = P^{-1}((X^TX))^{-1}(P^T)^{-1}  P^TX^T y$, используем  $A A^{-1} = E$    
$w_1 = P^{-1}((X^TX))^{-1}EX^T y$ , произведение единичной матрицы на любую дают эту любую   
$w_1 = P^{-1} * ((X^TX))^{-1}X^T y$ получили исходное значение $w_1$, что было выше



## Алгоритм преобразования

**Алгоритм**

1. Сгенерим рандом матрицу R 4х4 , пусть будет целочисленные значения.    
2. Проверим ее на обратимость   и найдем обратную $R^{-1}$.
3. Умножаем признаки на матрицу R , получаем закодированы персональные данные.
4. Умножаем закодированые признаки на обратную матрицу и  получаем исходные данные.

**Обоснование**

Потому как при умножении матрицу на обратной получаем единичную матрицу. А произведение любой мтарицы на единичную дает исходную матрицу.

## Проверка алгоритма

In [7]:
# генерация рандом матрицы (пусть будет  1 и 0)
#R = np.random.randint(10, size=(4,4))
R = np.random.normal(size=(4,4))
R

array([[-0.42630319,  1.20146019,  0.25560372, -0.90515311],
       [ 0.14632067,  0.44045408, -0.49482745, -0.09435681],
       [-2.80745701, -0.32174476,  0.60064408,  0.18065464],
       [ 1.61996045, -0.52555787,  0.12789027, -0.48211269]])

In [8]:
# проверяем и находим обратную
R_1 = np.linalg.inv(R)
R_1

array([[ 0.03338317, -0.57586848, -0.46238407, -0.12323176],
       [ 0.50623643, -0.89371713, -0.72845099, -1.04849186],
       [ 0.51811447, -2.66852081, -0.60946407, -0.67885025],
       [-0.30224328, -1.66861806, -0.92124784, -1.52538147]])

In [9]:
#разбивка на фьючи и таргет
features = df.drop(columns='Страховые выплаты')
target = df['Страховые выплаты']

In [10]:
# обучение модели на исходных данных и проверка r2_score
model = LinearRegression()
model.fit(features, target)
r2_score (target , model.predict(features))

0.42494550286668

In [11]:
#кодируем фичи
features_encoded = features.values @ R
features_encoded.shape

(5000, 4)

In [12]:
#таргет остается прежним
target_encoded = target
target_encoded.shape

(5000,)

In [13]:
#заново обучам модель и находим r2_score
model = LinearRegression()
model.fit(features_encoded, target_encoded)
r2_score(target_encoded , model.predict(features_encoded))

0.4249455028666772

**Как видим r2_score остался прежним.**

In [14]:
# разкодируем личные данные
features_decoded = features_encoded @ R_1

In [15]:
# разкодированные персональные данный
pd.DataFrame (features_decoded,  columns=features.columns).apply(np.round).astype(int)

Пол  Возраст  Зарплата  Члены семьи
0       1       41     49600            1
1       0       46     38000            1
2       0       29     21000            0
3       0       21     41700            2
4       1       28     26100            0
...   ...      ...       ...          ...
4995    0       28     35700            2
4996    0       34     52400            1
4997    0       20     33900            2
4998    1       22     32700            3
4999    1       28     40600            1

[5000 rows x 4 columns]

In [16]:
#сравним с исходными данными
features

Пол  Возраст  Зарплата  Члены семьи
0       1     41.0   49600.0            1
1       0     46.0   38000.0            1
2       0     29.0   21000.0            0
3       0     21.0   41700.0            2
4       1     28.0   26100.0            0
...   ...      ...       ...          ...
4995    0     28.0   35700.0            2
4996    0     34.0   52400.0            1
4997    0     20.0   33900.0            2
4998    1     22.0   32700.0            3
4999    1     28.0   40600.0            1

[5000 rows x 4 columns]

**Общий вывод:**      
Применно кодирование  персональных данных с помощью умножения  признаков на квадратную обратимую матрицу.  Воостановить данные можно умножив на обратную матрицу.    
Качество линейной регрессии при умножениии признаков на обратимую матрицу не меняется.

## Чек-лист проверки

Поставьте 'x' в выполненных пунктах. Далее нажмите Shift+Enter.

- [x]  Jupyter Notebook открыт
- [x]  Весь код выполняется без ошибок
- [x]  Ячейки с кодом расположены в порядке исполнения
- [x]  Выполнен шаг 1: данные загружены
- [x]  Выполнен шаг 2: получен ответ на вопрос об умножении матриц
    - [x]  Указан правильный вариант ответа
    - [x]  Вариант обоснован
- [x]  Выполнен шаг 3: предложен алгоритм преобразования
    - [x]  Алгоритм описан
    - [x]  Алгоритм обоснован
- [x]  Выполнен шаг 4: алгоритм проверен
    - [x]  Алгоритм реализован
    - [x]  Проведено сравнение качества моделей до и после преобразования